[terminal]
osc52 = "CopyPaste"

[font]
size = 13

[font.normal]
family = "DejaVuSansM Nerd Font"

[window.padding]
x = 5

[keyboard]
bindings = [
{	key = "Insert",	mods = "Shift",	action = "Paste" },
]
